# Introduction to Data Models in R

In this notebook, we will explore the concept of data models, starting from the basic idea of a table, moving on to joins, and finally discussing semi-structured formats like JSON. All examples will be demonstrated using R.

## 1. What is a Data Table?

A data table is a structured way to organize data in rows and columns, similar to a spreadsheet. Each row represents an observation, and each column represents a variable or attribute.

In [22]:
# Let's create a simple data frame (table) in R
customers <- data.frame(
  customer_id = 1:4,
  name = c("Alice", "Bob", "Charlie", "Diana"),
  age = c(20, 21, 19, 22)
)

# Display the data frame
customers

  customer_id name    age
1 1           Alice   20
2 2           Bob     21
3 3           Charlie 19
4 4           Diana   22

## 2. Relational Data and Joins

Often, data is split across multiple tables to reduce redundancy. These tables can be linked using keys (such as an ID column). Combining data from multiple tables is called a **join**.

In [23]:
# Create another table: student grades
rentals <- data.frame(
  customer_id = c(1, 2, 2, 3, 4, 4),
  course = c("Odyssey", "The Green Window", "Vickies Truth", "Odyssey", "Working Windows", "Time Before Time"),
  payment = c(1.90, 2.85, 2.08, 1.92, 3.95, 4.89)
)

rentals

  customer_id course           payment
1 1           Odyssey          1.90
2 2           The Green Window 2.85
3 2           Vickies Truth    2.08
4 3           Odyssey          1.92
5 4           Working Windows  3.95
6 4           Time Before Time 4.89

### Joining Tables in R

We can use the `dplyr` package to join tables. Let's join the `students` and `grades` tables to see each student's grades along with their names and ages.

In [24]:
library(dplyr)

# Perform an inner join on the 'id' column
customer_rentals <- inner_join(customers, rentals, by = "customer_id")

customer_rentals

  customer_id name    age course           payment
1 1           Alice   20  Odyssey          1.90
2 2           Bob     21  The Green Window 2.85
3 2           Bob     21  Vickies Truth    2.08
4 3           Charlie 19  Odyssey          1.92
5 4           Diana   22  Working Windows  3.95
6 4           Diana   22  Time Before Time 4.89

## 3. Long vs Wide Data Formats

When working with data in R (and in data science generally), you will often encounter two main ways to organize your data: **long** and **wide** formats.

### Wide Format
In the **wide format**, each subject or entity has a single row, and different variables or repeated measurements are stored in separate columns. This format is common in spreadsheets and is often used for data entry.

**Example:**

| id | name    | math_grade | english_grade |
|----|---------|------------|---------------|
| 1  | Alice   | 90         | 85            |
| 2  | Bob     | 78         | 88            |

### Long Format
In the **long format**, each row is a single observation, and repeated measurements are stacked in a single column. There is usually a column indicating the variable type (e.g., subject, test type).

**Example:**

| id | name  | subject  | grade |
|----|-------|----------|-------|
| 1  | Alice | math     | 90    |
| 1  | Alice | english  | 85    |
| 2  | Bob   | math     | 78    |
| 2  | Bob   | english  | 88    |

### Why Does Format Matter?
- **Wide format** is often easier for data entry and some types of analysis (e.g., regression with fixed variables).
- **Long format** is preferred for plotting (e.g., with ggplot2) and for many data manipulation tasks (e.g., grouping, summarizing).

R provides tools to convert between these formats, such as the `pivot_longer()` and `pivot_wider()` functions from the `tidyr` package.

# OLAP Cubes and Pivot Tables: Roll-Up and Drill-Down

OLAP (Online Analytical Processing) cubes and pivot tables are powerful tools for data analysis, enabling users to explore and summarize large datasets interactively. These tools are commonly used in business intelligence to gain insights from multidimensional data.

## Pivot Tables
A pivot table is a data summarization tool that allows you to reorganize and aggregate data dynamically. You can group data by different dimensions (such as time, product, or region) and calculate summary statistics (like sums, averages, or counts) for each group.

## OLAP Cubes
An OLAP cube is a multidimensional array of data, often used to represent data along multiple dimensions. For example, sales data might be analyzed by product, region, and time. OLAP cubes allow for fast querying and flexible analysis across these dimensions.

## Roll-Up and Drill-Down
- **Roll-Up**: This operation summarizes data by climbing up a hierarchy or by grouping data. For example, you might roll up daily sales data to see monthly or yearly totals. In a pivot table, this is like collapsing detailed rows into higher-level summaries.
- **Drill-Down**: This operation provides more detailed data by navigating down a hierarchy. For example, you might drill down from yearly sales to see sales by month, or from a product category to individual products. In a pivot table, this is like expanding a summary to reveal the underlying details.

These operations help users explore data at different levels of granularity, making it easier to identify trends, patterns, and outliers.

## A Special Example
A perfect example of roll-up and drill-down operations is how we analyze data over time. Time is often structured in a hierarchy, allowing us to aggregate (roll-up) or disaggregate (drill-down) data across different levels of granularity.

For instance, we might start with data at the hour or date level and then roll it up to broader time windows, such as 'after hours', weeks, months, or even quarters (Q1, Q2, etc.). Conversely, we can drill down from a yearly summary to see details by quarter, month, or even specific days or hours.

Special time tables or functions are often used to facilitate these operations, enabling us to group data into meaningful periods for analysis and reporting. This hierarchical approach to time makes it easy to gain insights at both high and detailed levels, depending on the analytical need.

## 4. Semi-Structured Data: JSON

Not all data fits neatly into tables. **Semi-structured data** like JSON allows for more flexible data representation, where each record can have a different structure.

In [28]:
# Example of JSON data in R
library(jsonlite)

# Create a list with varying structure
customer_profile <- list(
  list(id = 1, name = "Alice", favorite_genre = c("Horror", "Drama")),
  list(id = 2, name = "Bob", collector = TRUE),
  list(id = 3, name = "Charlie", age = 19, address = list(city = "Springfield", zip = "12345"))
)

# Convert to JSON
json_data <- toJSON(customer_profile, pretty = TRUE)
cat(json_data)

[
  {
    "id": [1],
    "name": ["Alice"],
    "favorite_genre": ["Horror", "Drama"]
  },
  {
    "id": [2],
    "name": ["Bob"],
    "collector": [true]
  },
  {
    "id": [3],
    "name": ["Charlie"],
    "age": [19],
    "address": {
      "city": ["Springfield"],
      "zip": ["12345"]
    }
  }
]

### Reading and Manipulating JSON in R

R can read and manipulate JSON data using the `jsonlite` package. Let's parse the JSON data back into an R object.

In [29]:
# Parse JSON back to R list
parsed_profiles <- fromJSON(json_data, simplifyDataFrame = FALSE)

# Display the parsed data
parsed_profiles

[[1]]
[[1]]$id
[1] 1

[[1]]$name
[1] "Alice"

[[1]]$favorite_genre
[1] "Horror" "Drama"


[[2]]
[[2]]$id
[1] 2

[[2]]$name
[1] "Bob"

[[2]]$collector
[1] TRUE


[[3]]
[[3]]$id
[1] 3

[[3]]$name
[1] "Charlie"

[[3]]$age
[1] 19

[[3]]$address
[[3]]$address$city
[1] "Springfield"

[[3]]$address$zip
[1] "12345"

JSON allows us to store nested and variable-length data, such as a list of courses for each student. This is useful when the structure of the data can change or when relationships are more complex.

## 5. Summary

- **Tables** organize data into rows and columns.
- **Relationships** connect data across tables using keys.
- **Joins** allow us to combine data from multiple tables.
- **Long vs Wide formats** represent different ways data can appear and then be converted to make analysis possible
- **Semi-structured formats** like JSON provide flexibility for complex or variable data.

Understanding these concepts is essential for working with data in both traditional databases and modern data systems.